### PR TITLE
Update treecompare.py

### PR DESCRIPTION
**Pull request by darrnz**
False positives and false negatives were mixed up.

### CODE REVIEW

**Comment by jeetsukumaran** [comment]
Current implementation follows the documentation, no? "    Counts and returns number of false positive bipar (bipartitions found in
    ``comparison_tree`` but not in ``reference_tree``) and false negative
    bipartitions (bipartitions found in ``reference_tree`` but not in
    ``comparison_tree``)"

**Comment by darrnz** [comment]
I believe my change makes it behave as indicated in the documentation. I was getting confusing results, so I tried with some test trees.

`ref_bipartitions.difference(comparison_bipartitions)` returns the bipartitions found in `ref_tree` but not in `comparison_tree`, so it gives you the false negatives, not the false positives.

But it is possible that I am still **very** confused :)

**Comment by jeetsukumaran** [comment]
Ah yes. OK. Mea culpa. You are right. The logic is as follows: the term "reference tree" implies that this the tree that sets the "truth" or "benchmark", to which the "comparison" tree is "referred". So a "false negative" should be splits found in the reference tree but NOT in the comparison tree. Conversely, a "false positive" should be splits that are found in the comparison tree and not in the reference tree.

**Comment by jeetsukumaran** [comment]
Fixed in development master: 7b6739b . Thanks!

**Pull request closed without merging**
