### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by wrightaprilm**
Instructions for installing dendropy to conda-managed environments. It's quite easy - you just import pip as a module in your Anaconda terminal or Jupyter notebook.

### CODE REVIEW

**Comment by jeetsukumaran** [comment]
Hi @wrightaprilm, thank you for this. Definitely useful. Only thing is, the RST links are not correct. Instead of, e.g.

    `conda package manager` <https://conda.io/docs/>

they should be:

    `conda package manager <https://conda.io/docs/>`_ 

I can accept the PR and fix it on my end, but I think it might be cleaner for you to edit your source and then it is a just a single accept?

**Comment by wrightaprilm** [comment]
Good catch, PR updated.

**Comment by jeetsukumaran** [comment]
Sorry, one last thing. Could you change "dendropy" to "DendroPy"? Consistent orthography in documentation helps reduce my OCD anxiety :(

**Comment by wrightaprilm** [comment]
Yep, no problem.

**Comment by jeetsukumaran** [comment]
Thanks!

**Comment by wrightaprilm** [comment]
Sure thing, I love DendroPy and the condaverse!

**Pull request merged**
